name: Main README builder
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build-readme
      - name: Commit README
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update README (auto)"
          add: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
